#!/bin/sh

echo "!!! hello from bootstrap"
env

set -euo pipefail

# Initialization - load function handler
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -vvvv -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  echo "EVENT DATA FROM RUNTIME: ${EVENT_DATA}"
  echo "HEADERS FROM RUNTIME:"
  cat $HEADERS

  EVENT_DATA=$(curl -vvvv -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  echo "EVENT DATA FROM RUNTIME (AGAIN): ${EVENT_DATA}"
  echo "HEADERS FROM RUNTIME (AGAIN):"
  cat $HEADERS

  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")

  # Send the response
  curl -s -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE" -o /dev/null
done
