service: ${file(serverless.config.cjs):SERVICE_NAME}

plugins:
  - serverless-dotenv-plugin
  - serverless-tsoa
  - serverless-esbuild
  - serverless-offline-resources
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
            - 'secretsmanager:*'
            - 'sns:*'
            - 'sqs:*'
          Resource: '*'
  stage: ${env:NODE_ENV, 'development'}
  logRetentionInDays: 1
  tracing:
    apiGateway: true
    lambda: true
  environment:
    QUEUE_URL: { Ref: Queue }
    TABLE_NAME: { Ref: Table }
    TOPIC_ARN: { Ref: Topic }
    SECRET_ID: { Ref: Secret }
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}

functions:
  webapp:
    handler: src/webapp.handler
    timeout: 29
    events:
      - httpApi:
          method: '*'
          path: /{proxy+}
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [Table, StreamArn]
      - sqs:
          arn:
            Fn::GetAtt: [Queue, Arn]
      - sns:
          arn: !Ref Topic
          topicName: ${self:service}-${self:provider.stage}
      - eventBridge:
          schedule: rate(5 minutes)

resources:
  Resources:
    Secret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: ${self:service}-${self:provider.stage}
        SecretString: ${file(serverless.config.cjs):SECRETS}

    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}

    Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}

    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        KeySchema:
          - AttributeName: hashKey
            KeyType: HASH
          - AttributeName: rangeKey
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: hashKey
            AttributeType: S
          - AttributeName: rangeKey
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: rangeKey-hashKey-index
            KeySchema:
              - AttributeName: rangeKey
                KeyType: HASH
              - AttributeName: hashKey
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: uuid-index
            KeySchema:
              - AttributeName: uuid
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true
        BillingMode: PAY_PER_REQUEST

custom:
  serverless-offline:
    host: 0.0.0.0
    reloadHandler: true
    useChildProcesses: false

  esbuild:
    bundle: true
    minify: true
    sourcemap: external
    loader:
      .html: text

  tsoa:
    reloadHandler: true
    spec:
      basePath: '/'
      name: ${self:service}
      version: ${file(serverless.config.cjs):VERSION}
      entryFile: src/app.ts
      noImplicitAdditionalProperties: throw-on-extras
      controllerPathGlobs: ['src/api/index.ts', 'src/api/*-api.ts']
      outputDirectory: src/lib
      specFileBaseName: 'openapi'
      specVersion: 3
      securityDefinitions:
        jwt:
          type: http
          scheme: bearer
          bearerFormat: JWT
    routes:
      entryFile: src/app.ts
      noImplicitAdditionalProperties: throw-on-extras
      controllerPathGlobs: ['src/api/index.ts', 'src/api/*-api.ts']
      routesDir: src/api/express
      authenticationModule: src/api/express/auth.ts
      noWriteIfUnchanged: true
    client:
      target: src/lib/api.ts
