name: 'Deploy'

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - development
      - production
  push:
    branches:
      - development
      - production

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn

      - uses: scaffoldly/deploy-action@v1
        with:
          role: ${{ vars.DEPLOYMENT_ROLE }}
          cli: serverless
        env:
          SECRETS: ${{ toJSON(secrets) }}
          NODE_ENV: production
