name: 'Deploy'

on:
  workflow_dispatch: {}
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v4

      - id: branch-names
        uses: tj-actions/branch-names@v8

      - uses: saml-to/assume-aws-role-action@v1
        with:
          role: arn:aws:iam::471112697609:role/OrganizationAccountAccessRole
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - run: yarn

      # - run: echo "${{ toJSON(secrets) }}" > .ci-secrets
      #   working-directory: /tmp

      - run: echo ${{ steps.branch-names.outputs.current_branch }}
      # - run: yarn deploy --stage ${{ steps.branch-names.outputs.current_branch }}
