name: 'Deploy (Internal)'

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy the stack
        default: false
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - express
      - react-vite
      - angular
  push:
    branches:
      - express
      - react-vite
      - angular

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - run: yarn

      - uses: scaffoldly/deploy-action@main
        with:
          role: ${{ vars.DEPLOYMENT_ROLE }}
          cli: serverless
        env:
          SECRETS: ${{ toJSON(secrets) }}
          NODE_ENV: production
