name: 'Deploy (Internal)'

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy the stack instead of deploying
        default: false
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - express
      - react-vite
      - angular

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn

      - id: deploy
        uses: scaffoldly/deploy-action@main
        with:
          role: ${{ vars.DEPLOYMENT_ROLE }}

      - if: ${{ steps.deploy.outputs.deploy == 'true' }}
        run: yarn deploy --verbose --stage ${{ steps.deploy.outputs.stage }}
        env:
          SECRETS: ${{ toJSON(secrets) }}
          NODE_ENV: production

      - if: ${{ steps.deploy.outputs.destroy == 'true' }}
        run: yarn destroy --verbose --stage ${{ steps.deploy.outputs.stage }}
