name: 'Deploy (Internal)'

on:
  workflow_dispatch: {}
  push:
    branches:
      - express
      - react-vite
      - angular

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v4

      - id: branch-names
        uses: tj-actions/branch-names@v8

      - uses: scaffoldly/deploy-action@main

      - uses: saml-to/assume-aws-role-action@v1
        with:
          role: ${{ vars.DEPLOYMENT_ROLE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn

      - run: yarn deploy --verbose --stage ${{ steps.branch-names.outputs.current_branch }}
        env:
          SECRETS: ${{ toJSON(secrets) }}
          NODE_ENV: production
