name: 'Deploy (Internal)'

on:
  workflow_dispatch: {}
  push:
    branches:
      - express
      - react-vite
      - angular

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn

      - id: deploy
        uses: scaffoldly/deploy-action@main
        with:
          role: ${{ vars.DEPLOYMENT_ROLE }}

      - run: yarn deploy --verbose --stage ${{ steps.deploy.outputs.stage }}
        env:
          SECRETS: ${{ toJSON(secrets) }}
          NODE_ENV: production
